version: "3.8"

volumes:
  home_node_modules:
  news_node_modules:
  shop_node_modules:
  travel_node_modules:
  dsp_node_modules:
  ssp_node_modules:

services:
  home:
    image: gcr.io/privacy-sandcastle-home/sandcastle_home:latest
    build: ./servers/home
    container_name: "sandcastle_home"
    env_file:
      - .env
    volumes:
      - ./servers/home:/workspace
      - home_node_modules:/workspace/node_modules

  news:
    image: gcr.io/privacy-sandcastle-news/sandcastle_news:latest
    build: ./servers/news
    container_name: "sandcastle_news"
    env_file:
      - .env
    volumes:
      - ./servers/news:/workspace
      - news_node_modules:/workspace/node_modules

  shop:
    image: gcr.io/privacy-sandcastle-shop/sandcastle_shop:latest
    build: ./servers/shop
    container_name: "sandcastle_shop"
    env_file:
      - .env
    environment:
      - host=${SHOP_HOST}
      - token=${SHOP_TOKEN}
    volumes:
      - ./servers/shop:/workspace
      - shop_node_modules:/workspace/node_modules

  travel:
    image: gcr.io/privacy-sandcastle-travel/sandcastle_travel:latest
    build: ./servers/travel
    container_name: "sandcastle_travel"
    env_file:
      - .env
    environment:
      - host=${TRAVEL_HOST}
      - token=${TRAVEL_TOKEN}
    volumes:
      - ./servers/travel:/workspace
      - travel_node_modules:/workspace/node_modules

  dsp:
    image: gcr.io/privacy-sandcastle-dsp/sandcastle_dsp:latest
    build: ./servers/dsp
    container_name: "sandcastle_dsp"
    env_file:
      - .env
    environment:
      - host=${DSP_HOST}
      - token=${DSP_TOKEN}
    volumes:
      - ./servers/dsp:/workspace
      - dsp_node_modules:/workspace/node_modules

  ssp:
    image: gcr.io/privacy-sandcastle-ssp/sandcastle_ssp:latest
    build: ./servers/ssp
    container_name: "sandcastle_ssp"
    env_file:
      - .env
    volumes:
      - ./servers/ssp:/workspace
      - ssp_node_modules:/workspace/node_modules

  nginx:
    image: nginx:1.22.1-alpine
    container_name: "sandcastle_proxy"
    volumes:
      # using env variables in nginx config
      - type: bind
        source: "./nginx/nginx.conf"
        target: "/etc/nginx/templates/default.conf.template"
      - type: bind
        source: "./nginx/cert"
        target: "/cert"
    ports:
      - "${PORT}:443"
    env_file:
      - .env
