version: '3.8'

services:
  home:
    build: ../servers/home
    container_name: 'sandcastle_home'
    environment:
      - host=${HOME_HOST}
      - port=${HOME_PORT}

  publisher:
    build: ../servers/publisher
    container_name: 'sandcastle_publisher'
    environment:
      - host=${PUBLISHER_HOST}
      - port=${PUBLISHER_PORT}

  advertizer:
    build: ../servers/advertizer
    container_name: 'sandcastle_advertizer'
    environment:
      - host=${ADVERTIZER_HOST}
      - port=${ADVERTIZER_PORT}

  dsp:
    build: ../servers/dsp
    container_name: 'sandcastle_dsp'
    environment:
      - host=${DSP_HOST}
      - port=${DSP_PORT}

  ssp:
    build: ../servers/ssp
    container_name: 'sandcastle_ssp'
    environment:
      - host=${SSP_HOST}
      - port=${SSP_PORT}

  nginx:
    image: nginx:stable-alpine
    container_name: 'sandcastle_proxy'
    volumes:
      # using env variables in nginx config
      - type: bind
        source: "../nginx/nginx.conf"
        target: "/etc/nginx/templates/default.conf.template"
      - type: bind
        source: "../nginx/cert"
        target: "/cert"
    ports:
      - '80:80'
      - '443:443'
      - '3000:80'
      - '4000:443'
    environment:
      # for nginx template
      - HOME_HOST=${HOME_HOST}
      - HOME_PORT=${HOME_PORT}
      - PUBLISHER_HOST=${PUBLISHER_HOST}
      - PUBLISHER_PORT=${PUBLISHER_PORT}
      - ADVERTIZER_HOST=${ADVERTIZER_HOST}
      - ADVERTIZER_PORT=${ADVERTIZER_PORT}
      - DSP_HOST=${DSP_HOST}
      - DSP_PORT=${DSP_PORT}
      - SSP_HOST=${SSP_HOST}
      - SSP_PORT=${SSP_PORT}
