version: '3.8'

services:
  home:
    build: ../servers/home
    container_name: 'sandcastle_home'
    environment:
      - host=${HOME_HOST}
      - port=${HOME_PORT}

  publisher:
    build: ../servers/publisher
    container_name: 'sandcastle_publisher'
    environment:
      - host=${PUBLISHER_HOST}
      - port=${PUBLISHER_PORT}

  shop:
    build: ../servers/shop
    container_name: 'sandcastle_shop'
    environment:
      - host=${SHOP_HOST}
      - port=${SHOP_PORT}

  travel:
    build: ../servers/travel
    container_name: 'sandcastle_travel'
    environment:
      - host=${TRAVEL_HOST}
      - port=${TRAVEL_PORT}

  dsp:
    build: ../servers/dsp
    container_name: 'sandcastle_dsp'
    environment:
      - host=${DSP_HOST}
      - port=${DSP_PORT}

  ssp:
    build: ../servers/ssp
    container_name: 'sandcastle_ssp'
    environment:
      - host=${SSP_HOST}
      - port=${SSP_PORT}

  nginx:
    image: nginx:stable-alpine
    container_name: 'sandcastle_proxy'
    volumes:
      # using env variables in nginx config
      - type: bind
        source: "../nginx/nginx.conf"
        target: "/etc/nginx/templates/default.conf.template"
      - type: bind
        source: "../nginx/cert"
        target: "/cert"
    ports:
      - '80:80'
      - '443:443'
      - '3000:80'
      - '4000:443'
    environment:
      # for nginx template
      ## home
      - HOME_HOST=${HOME_HOST}
      - HOME_PORT=${HOME_PORT}
      ## publisher
      - PUBLISHER_HOST=${PUBLISHER_HOST}
      - PUBLISHER_PORT=${PUBLISHER_PORT}
      ## shop
      - SHOP_HOST=${SHOP_HOST}
      - SHOP_PORT=${SHOP_PORT}
      ## travel
      - TRAVEL_HOST=${TRAVEL_HOST}
      - TRAVEL_PORT=${TRAVEL_PORT}
      ## dsp
      - DSP_HOST=${DSP_HOST}
      - DSP_PORT=${DSP_PORT}
      ## ssp
      - SSP_HOST=${SSP_HOST}
      - SSP_PORT=${SSP_PORT}
